@startuml
'https://plantuml.com/sequence-diagram

autonumber

首页 -> 通讯录 :点击通讯录按钮
通讯录 -> 添加部门: 点击+按钮
首页 -> 导入通讯录: 点击导入通讯录按钮
首页 -> 添加成员: 点击添加成员按钮

添加部门-> 通讯录: 填写部门保存
通讯录 <-- 通讯录: 获取部门信息
导入通讯录 -> 通讯录: 点击保存
通讯录 <-- 通讯录: 检测导入信息
添加成员 -> 通讯录: 点击成员保存


通讯录 <-- 通讯录: 获取成员信息
@enduml